language: node_js
sudo: required
node_js:
  - "6"
env:
  before_install:
    - openssl aes-256-cbc -K $encrypted_4d472037f3cf_key -iv $encrypted_4d472037f3cf_iv -in .env.enc -out .env -d
install:
  - npm install
script:
  - npm test
cache:
  directories:
    - node_modules
before_deploy: apt-get install lftp
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
